services:
  node:
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USER=api
      - DB_PASSWORD=apidev
      - DB_NAME=ajamiyat
    command: npm run dev